### ISSUE TITLE
maxTTL does not expire based on time

### ISSUE THREAD

**Issue by david-alpert-nl** [naugtur/safe-memory-cache#3]
The `maxTTL` parameter does not seem to evict items based on time.

If I am periodically accessing the cached item I am able to keep the item in cache well beyond the configured `maxTTL` value.

is there a way to set an actual maximum time-based eviction policy on this in-memory cache?

**Comment by naugtur** [comment]
Accessing an item keeps moving it to the newest bucket and it's never going away. 
Items in this cache are not removed individually. They're stores in buckets and oldest bucket gets removed.
Max TTL is the time it takes for all buckets to be removed.
New buckets get added each time and new or accessed items are places in newest bucket.

There is no precise TTL involved. 
I recall there are other catches like this one with different priorities and you might find one that does individual items TTL.
This one is optimized for smooth garbage collection.

**Comment by david-alpert-nl** [comment]
closing as: "working as designed"
